# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: API Build

on:
  push:
    branches: [master]
    paths: api/**
  pull_request:
    branches: [master]
    paths: api/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: APP Build
        working-directory: ./app
        run: |
          npm install
          npm run build

      - name: API Build
        working-directory: ./api
        run: |
          npm install
          npm run build
